#!/bin/bash

NAME="Erik Wernersson"
EMAIL="https://github.com/elgw/nua/issues"

set -e # exit on error

if [ $EUID = 0 ]; then
    echo "WARNING: You are running as root, please abort!"
    echo "Sleeping for 10 s"
    sleep 10
fi

savedir="$(pwd)"
builddir=$(mktemp -d)
cd $builddir
pkgdir=$(mktemp -d)/libnua
echo "pkgdir=$pkgdir"

ver_major=`sed -rn 's/^#define.*NUA_VERSION_MAJOR.*([0-9]+).*$/\1/p' < $savedir/src/nua_version.h`
ver_minor=`sed -rn 's/^#define.*NUA_VERSION_MINOR.*([0-9]+).*$/\1/p' < $savedir/src/nua_version.h`
ver_patch=`sed -rn 's/^#define.*NUA_VERSION_PATCH.*([0-9]+).*$/\1/p' < $savedir/src/nua_version.h`
pkgver="${ver_major}.${ver_minor}.${ver_patch}"
echo "pkgver=$pkgver"
arch=$(dpkg --print-architecture)
echo "arch=$arch"

# Copy files to the correct places
# binary
mkdir -p $pkgdir/usr/local/bin
cp $savedir/nuademo $pkgdir/usr/local/bin/nuademo
# libraries
mkdir -p $pkgdir/usr/local/lib
cp $savedir/libnua.so $pkgdir/usr/local/lib/
# headers
mkdir -p $pkgdir/usr/local/include/libnua
cp $savedir/src/*.h $pkgdir/usr/local/include/libnua
mkdir -p $pkgdir/usr/local/include/libnua/kazmath/
cp $savedir/src/kazmath/*.h $pkgdir/usr/local/include/libnua/kazmath/

# man pages
# mkdir -p $pkgdir/usr/share/man/man1/
# cp $savedir/doc/libnua.1 $pkgdir/usr/share/man/man1/

cd $pkgdir
size=$(du -k usr | tail -n1 | sed 's/usr//')

mkdir $pkgdir/DEBIAN/
cat > $pkgdir/DEBIAN/control << END
Package: libnua
Version: $pkgver
Architecture: $arch
Depends: libsdl2-2.0-0, libsdl2-image-2.0-0, libvulkan1, libxml2
Conflicts:
Maintainer: $NAME <$EMAIL>
Installed-Size: $size
Section: custom
Priority: optional
Homepage: https://github.com/elgw/nua/
Description: A library to show beads
END

cd $pkgdir/../
dpkg-deb --build libnua libnua_${pkgver}_${arch}.deb
mv libnua_${pkgver}_${arch}.deb "$savedir"
